# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2

pipelines:
  branches:
    unit-tests:
      - step:
          caches:
            - composer
          script:
            # install necessary packages
            - apt-get update && apt-get install -qqy git unzip openssh-client
            # get ssh keys for git
            - mkdir -p ~/.ssh
            - (umask  077 ; echo $PIPELINES_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
            - ssh-keyscan -t rsa -H bitbucket.org >> ~/.ssh/known_hosts
            # install composer and packages
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            # install codesniffer rules (enable only when there are not many warnings)
            #- git clone git@bitbucket.org:incsub/wpmudev-dev-tools.git ~/phpcs-rules
            #- vendor/bin/phpcs --colors --sniffs=~/phpcs-rules/Wpmudev-Plugins-Standard/ruleset.xml src/ wp-smush.php
            - php -S localhost:8085 --docroot public &>/dev/null&
            - vendor/bin/codecept run